version: '3.6'
services:

  viewer:
    build: .
    image: ohif_openresty:latest
    container_name: viewer
    depends_on:
      - keycloak
      - orthanc
    restart: always
    ports:
      - '80:80'    
    volumes:
      - ./config/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro     
      - ./volumes/logs/nginx:/var/logs/nginx      
      - ./config/docker_openresty-orthanc-keycloak.js:/var/www/html/app-config.js:ro

  orthanc:
    image: jodogne/orthanc-plugins:1.6.0
    container_name: orthanc    
    restart: always
    depends_on:
      - keycloak      
    volumes:      
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
    command: /etc/orthanc/orthanc.json

## ONLY FOR CREATING KEYCLOAK META DATA. This will export seed value for realm and will create a test user.
  keycloakutils:
    image: jboss/keycloak:9.0.2
    hostname: keycloakutils
    container_name: keycloakutils    
    volumes:        
      - ./config/realm-export.json:/tmp/realm-export.json
    depends_on:
      - keycloak
    entrypoint: sh -c "sleep 30; /opt/jboss/keycloak/bin/kcadm.sh config credentials --server http://keycloak:8080/auth --realm master --user admin --password password && /opt/jboss/keycloak/bin/kcadm.sh create realms -s realm=OHIF -s enabled=true && /opt/jboss/keycloak/bin/kcadm.sh create partialImport -r OHIF -s ifResourceExists=OVERWRITE -o -f /tmp/realm-export.json && /opt/jboss/keycloak/bin/kcadm.sh create users -r OHIF -s username=test -s enabled=true && /opt/jboss/keycloak/bin/kcadm.sh set-password -r OHIF --username test --new-password test"

  keycloak:
    image: jboss/keycloak:9.0.2
    hostname: keycloak
    container_name: keycloak
    volumes:      
      - ./volumes/keycloak-themes/ohif:/opt/jboss/keycloak/themes/ohif      
      - ./config/realm-export.json:/tmp/realm-export.json
    environment:
      # Database
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: keycloak
      DB_PASSWORD: password
      # Keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      # KEYCLOAK_IMPORT: /tmp/ohif-keycloak-realm.json
      # KEYCLOAK_IMPORT: /tmp/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      # KEYCLOAK_WELCOME_THEME: <theme-name>
      # KEYCLOAK_DEFAULT_THEME: <theme-name>
      # KEYCLOAK_HOSTNAME: (recommended in prod)
      # KEYCLOAK_LOGLEVEL: DEBUG
      PROXY_ADDRESS_FORWARDING: 'true'
    depends_on:
      - postgres
    restart: unless-stopped

  # LINK: https://hub.docker.com/_/postgres/
  postgres:
    image: postgres:11.2
    hostname: postgres
    container_name: postgres
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: unless-stopped


